#FROM node:8.0
FROM ubuntu:xenial

ENV ROOTDIR /usr/local/
ENV GDAL_VERSION 2.2.0

# Install Node.js
RUN apt-get update
RUN apt-get install --yes curl
RUN apt-get install --yes sudo
RUN curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential

# Install GDAL
WORKDIR $ROOTDIR/
RUN apt-get install --yes software-properties-common
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update
RUN apt-get install --yes gdal-bin python-gdal

# Ecoset
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Bundle app source
ADD ./package.json /usr/src/app/package.json
ADD ./api /usr/src/app/api
ADD ./test /usr/src/app/test

# Install app dependencies
RUN npm install
WORKDIR /usr/src/app/api
RUN npm install
WORKDIR /usr/src/app/test
RUN npm install

WORKDIR /usr/src/app

CMD [ "npm", "test" ]